DZE_CLICK_ACTIONS = [
    ["ItemGPS","Scan Nearby","if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1500;};DZE_CLICK_ACTIONS_ZOMBIE_COUNT = count ((position player) nearEntities ['zZombie_Base',DZE_CLICK_ACTIONS_GPS_RANGE]); DZE_CLICK_ACTIONS_MAN_COUNT = count ((position player) nearEntities ['CAManBase',DZE_CLICK_ACTIONS_GPS_RANGE]);cutText[format['Within %1 Meters: %2 AI/players, %3 zombies, %4 vehicles',DZE_CLICK_ACTIONS_GPS_RANGE,DZE_CLICK_ACTIONS_MAN_COUNT - DZE_CLICK_ACTIONS_ZOMBIE_COUNT,count ((position player) nearEntities ['zZombie_Base',DZE_CLICK_ACTIONS_GPS_RANGE]),count ((position player) nearEntities ['allVehicles',DZE_CLICK_ACTIONS_GPS_RANGE]) - DZE_CLICK_ACTIONS_MAN_COUNT],'PLAIN DOWN'];","true"],
    ["ItemGPS","Range Up"   ,"if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1500;};DZE_CLICK_ACTIONS_GPS_RANGE = (DZE_CLICK_ACTIONS_GPS_RANGE + 100) min 2500; cutText[format['GPS RANGE: %1',DZE_CLICK_ACTIONS_GPS_RANGE],'PLAIN DOWN'];","true"],
    ["ItemGPS","Range Down" ,"if(isNil 'DZE_CLICK_ACTIONS_GPS_RANGE') then {DZE_CLICK_ACTIONS_GPS_RANGE = 1500;};DZE_CLICK_ACTIONS_GPS_RANGE = (DZE_CLICK_ACTIONS_GPS_RANGE - 100) max 1000;  cutText[format['GPS RANGE: %1',DZE_CLICK_ACTIONS_GPS_RANGE],'PLAIN DOWN'];","true"],
	["ItemToolbox","Flip Vehicle","execVM 'scripts\flipvehicle\flipvehicle.sqf';","true"],
	["ItemRadio","Group Management","execVM 'scripts\dzgm\loadGroupManagement.sqf';","true"],
	/* Combine Currency */
	["ItemGoldBar","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar2oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar3oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar4oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar5oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],	
	["ItemGoldBar6oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar7oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar8oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar9oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemGoldBar10oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],	
	["ItemSilverBar2oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar3oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar4oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar5oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],	
	["ItemSilverBar6oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar7oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar8oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar9oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemSilverBar10oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],	
	["ItemBriefcaseEmpty","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase10oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase20oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase30oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase40oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase50oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase60oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase70oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase80oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase90oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcase100oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS10oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS20oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS30oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS40oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS50oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS60oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS70oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS80oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS90oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"],
	["ItemBriefcaseS100oz","Combine Currency","execVM 'scripts\currency\combinecurrency.sqf';","true"]
];